// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHSTYsC3IwAZDOZ9xFVkxCynlHc5bXsRs',
    appId: '1:992910568802:web:71b4ca56b2e97480eb503b',
    messagingSenderId: '992910568802',
    projectId: 'g-stock-35175',
    authDomain: 'g-stock-35175.firebaseapp.com',
    storageBucket: 'g-stock-35175.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWpgZE2R8THfOKJ9sMm0KCDMro7ou5Iio',
    appId: '1:992910568802:android:46d3d2f9eb2a4e7beb503b',
    messagingSenderId: '992910568802',
    projectId: 'g-stock-35175',
    storageBucket: 'g-stock-35175.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_AeLmB2Jjgfl60LarvxTuVWHycxv_UVU',
    appId: '1:992910568802:ios:2dc81f33a0864cc7eb503b',
    messagingSenderId: '992910568802',
    projectId: 'g-stock-35175',
    storageBucket: 'g-stock-35175.firebasestorage.app',
    iosBundleId: 'com.example.gstock',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_AeLmB2Jjgfl60LarvxTuVWHycxv_UVU',
    appId: '1:992910568802:ios:2dc81f33a0864cc7eb503b',
    messagingSenderId: '992910568802',
    projectId: 'g-stock-35175',
    storageBucket: 'g-stock-35175.firebasestorage.app',
    iosBundleId: 'com.example.gstock',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHSTYsC3IwAZDOZ9xFVkxCynlHc5bXsRs',
    appId: '1:992910568802:web:80c65da597fe1691eb503b',
    messagingSenderId: '992910568802',
    projectId: 'g-stock-35175',
    authDomain: 'g-stock-35175.firebaseapp.com',
    storageBucket: 'g-stock-35175.firebasestorage.app',
  );

}